nelmio_api_doc:
    documentation:
        info:
            title: H2HTECH
            version: 1.0.0
    areas:
        default:
            path_patterns:
                - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
    html_config:
        swagger_ui_config:
            tryItOutEnabled: true
